include $(TOPDIR)/rules.mk
	
LUCI_TITLE:=Web UI for socat
LUCI_DEPENDS:=+socat +luci-compat
PKG_VERSION:=1.1-2021-10-30
	
include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
